<?php
/**
 * Created by PhpStorm.
 * User: Hary Fenitra
 * Date: 06/10/2022
 * Time: 11:35
 */

namespace App\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;

class ProductAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        $form->add('title'); // TODO: Change the autogenerated stub
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list->add('title');// TODO: Change the autogenerated stub
    }

}